name: Server CI
on:
  push:
    branches:
      - main
    paths:
      - src/server/**

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
  PROJECT_NAME: orderingapp-backend
  RUN_REGION: europe-central2
  SA_KEY_JSON: ${{ secrets.GCR_SA_KEY_JSON }}
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCR_PROJECT_ID }}

      # Build and push image to Google Container Registry
      - name: Build
        run: cd src/server && gcloud builds submit --tag gcr.io/$PROJECT_ID/$PROJECT_NAME

      - name: Deploy
        run: cd src/server && gcloud run deploy $PROJECT_NAME --image gcr.io/$PROJECT_ID/$PROJECT_NAME --platform managed --region $RUN_REGION
